/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.calc;

public class Calculator {
    private final double num2;
    private final double num1;
    
    public Calculator(double num1, double num2) {
        this.num1 = num1;
        this.num2 = num2;
    }
    
    public double add() {
        return this.num1 + this.num2;
    }
}
