/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.calc;

import org.junit.Test;
import static org.junit.Assert.*;

public class CalculatorTest {
    @Test public void testAdd() {
        Calculator calculator = new Calculator(3, 2);
        assertEquals(6, calculator.add(), 0);
    }
}
